package demo.model;

import java.math.BigDecimal;
import java.util.Date;

// 订单明细表
public class Item {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column item.id
     *
     * @mbggenerated Thu Nov 28 09:31:39 CST 2019
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column item.user_id
     *
     * @mbggenerated Thu Nov 28 09:31:39 CST 2019
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column item.order_no
     *
     * @mbggenerated Thu Nov 28 09:31:39 CST 2019
     */
    private Long orderNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column item.product_id
     *
     * @mbggenerated Thu Nov 28 09:31:39 CST 2019
     */
    private Integer productId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column item.product_name
     *
     * @mbggenerated Thu Nov 28 09:31:39 CST 2019
     */
    private String productName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column item.product_image
     *
     * @mbggenerated Thu Nov 28 09:31:39 CST 2019
     */
    private String productImage;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column item.current_unit_price
     *
     * @mbggenerated Thu Nov 28 09:31:39 CST 2019
     */
    private BigDecimal currentUnitPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column item.quantity
     *
     * @mbggenerated Thu Nov 28 09:31:39 CST 2019
     */
    private Integer quantity;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column item.total_price
     *
     * @mbggenerated Thu Nov 28 09:31:39 CST 2019
     */
    private BigDecimal totalPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column item.create_time
     *
     * @mbggenerated Thu Nov 28 09:31:39 CST 2019
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column item.update_time
     *
     * @mbggenerated Thu Nov 28 09:31:39 CST 2019
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column item.id
     *
     * @return the value of item.id
     *
     * @mbggenerated Thu Nov 28 09:31:39 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column item.id
     *
     * @param id the value for item.id
     *
     * @mbggenerated Thu Nov 28 09:31:39 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column item.user_id
     *
     * @return the value of item.user_id
     *
     * @mbggenerated Thu Nov 28 09:31:39 CST 2019
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column item.user_id
     *
     * @param userId the value for item.user_id
     *
     * @mbggenerated Thu Nov 28 09:31:39 CST 2019
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column item.order_no
     *
     * @return the value of item.order_no
     *
     * @mbggenerated Thu Nov 28 09:31:39 CST 2019
     */
    public Long getOrderNo() {
        return orderNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column item.order_no
     *
     * @param orderNo the value for item.order_no
     *
     * @mbggenerated Thu Nov 28 09:31:39 CST 2019
     */
    public void setOrderNo(Long orderNo) {
        this.orderNo = orderNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column item.product_id
     *
     * @return the value of item.product_id
     *
     * @mbggenerated Thu Nov 28 09:31:39 CST 2019
     */
    public Integer getProductId() {
        return productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column item.product_id
     *
     * @param productId the value for item.product_id
     *
     * @mbggenerated Thu Nov 28 09:31:39 CST 2019
     */
    public void setProductId(Integer productId) {
        this.productId = productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column item.product_name
     *
     * @return the value of item.product_name
     *
     * @mbggenerated Thu Nov 28 09:31:39 CST 2019
     */
    public String getProductName() {
        return productName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column item.product_name
     *
     * @param productName the value for item.product_name
     *
     * @mbggenerated Thu Nov 28 09:31:39 CST 2019
     */
    public void setProductName(String productName) {
        this.productName = productName == null ? null : productName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column item.product_image
     *
     * @return the value of item.product_image
     *
     * @mbggenerated Thu Nov 28 09:31:39 CST 2019
     */
    public String getProductImage() {
        return productImage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column item.product_image
     *
     * @param productImage the value for item.product_image
     *
     * @mbggenerated Thu Nov 28 09:31:39 CST 2019
     */
    public void setProductImage(String productImage) {
        this.productImage = productImage == null ? null : productImage.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column item.current_unit_price
     *
     * @return the value of item.current_unit_price
     *
     * @mbggenerated Thu Nov 28 09:31:39 CST 2019
     */
    public BigDecimal getCurrentUnitPrice() {
        return currentUnitPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column item.current_unit_price
     *
     * @param currentUnitPrice the value for item.current_unit_price
     *
     * @mbggenerated Thu Nov 28 09:31:39 CST 2019
     */
    public void setCurrentUnitPrice(BigDecimal currentUnitPrice) {
        this.currentUnitPrice = currentUnitPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column item.quantity
     *
     * @return the value of item.quantity
     *
     * @mbggenerated Thu Nov 28 09:31:39 CST 2019
     */
    public Integer getQuantity() {
        return quantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column item.quantity
     *
     * @param quantity the value for item.quantity
     *
     * @mbggenerated Thu Nov 28 09:31:39 CST 2019
     */
    public void setQuantity(Integer quantity) {
        this.quantity = quantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column item.total_price
     *
     * @return the value of item.total_price
     *
     * @mbggenerated Thu Nov 28 09:31:39 CST 2019
     */
    public BigDecimal getTotalPrice() {
        return totalPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column item.total_price
     *
     * @param totalPrice the value for item.total_price
     *
     * @mbggenerated Thu Nov 28 09:31:39 CST 2019
     */
    public void setTotalPrice(BigDecimal totalPrice) {
        this.totalPrice = totalPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column item.create_time
     *
     * @return the value of item.create_time
     *
     * @mbggenerated Thu Nov 28 09:31:39 CST 2019
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column item.create_time
     *
     * @param createTime the value for item.create_time
     *
     * @mbggenerated Thu Nov 28 09:31:39 CST 2019
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column item.update_time
     *
     * @return the value of item.update_time
     *
     * @mbggenerated Thu Nov 28 09:31:39 CST 2019
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column item.update_time
     *
     * @param updateTime the value for item.update_time
     *
     * @mbggenerated Thu Nov 28 09:31:39 CST 2019
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    @Override
    public String toString() {
        return "Item{" +
                "id=" + id +
                ", userId=" + userId +
                ", orderNo=" + orderNo +
                ", productId=" + productId +
                ", productName='" + productName + '\'' +
                ", productImage='" + productImage + '\'' +
                ", currentUnitPrice=" + currentUnitPrice +
                ", quantity=" + quantity +
                ", totalPrice=" + totalPrice +
                ", createTime=" + createTime +
                ", updateTime=" + updateTime +
                '}';
    }
}