package demo.model;

import java.math.BigDecimal;
import java.util.Date;

public class Ordered {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ordered.id
     *
     * @mbggenerated Sat Dec 21 16:33:27 CST 2019
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ordered.order_no
     *
     * @mbggenerated Sat Dec 21 16:33:27 CST 2019
     */
    private Long orderNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ordered.user_id
     *
     * @mbggenerated Sat Dec 21 16:33:27 CST 2019
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ordered.shipping_id
     *
     * @mbggenerated Sat Dec 21 16:33:27 CST 2019
     */
    private Integer shippingId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ordered.payment
     *
     * @mbggenerated Sat Dec 21 16:33:27 CST 2019
     */
    private BigDecimal payment;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ordered.payment_type
     *
     * @mbggenerated Sat Dec 21 16:33:27 CST 2019
     */
    private Integer paymentType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ordered.postage
     *
     * @mbggenerated Sat Dec 21 16:33:27 CST 2019
     */
    private Integer postage;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ordered.status
     *
     * @mbggenerated Sat Dec 21 16:33:27 CST 2019
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ordered.payment_time
     *
     * @mbggenerated Sat Dec 21 16:33:27 CST 2019
     */
    private Date paymentTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ordered.send_time
     *
     * @mbggenerated Sat Dec 21 16:33:27 CST 2019
     */
    private Date sendTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ordered.end_time
     *
     * @mbggenerated Sat Dec 21 16:33:27 CST 2019
     */
    private Date endTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ordered.close_time
     *
     * @mbggenerated Sat Dec 21 16:33:27 CST 2019
     */
    private Date closeTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ordered.create_time
     *
     * @mbggenerated Sat Dec 21 16:33:27 CST 2019
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ordered.update_time
     *
     * @mbggenerated Sat Dec 21 16:33:27 CST 2019
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ordered.id
     *
     * @return the value of ordered.id
     *
     * @mbggenerated Sat Dec 21 16:33:27 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ordered.id
     *
     * @param id the value for ordered.id
     *
     * @mbggenerated Sat Dec 21 16:33:27 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ordered.order_no
     *
     * @return the value of ordered.order_no
     *
     * @mbggenerated Sat Dec 21 16:33:27 CST 2019
     */
    public Long getOrderNo() {
        return orderNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ordered.order_no
     *
     * @param orderNo the value for ordered.order_no
     *
     * @mbggenerated Sat Dec 21 16:33:27 CST 2019
     */
    public void setOrderNo(Long orderNo) {
        this.orderNo = orderNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ordered.user_id
     *
     * @return the value of ordered.user_id
     *
     * @mbggenerated Sat Dec 21 16:33:27 CST 2019
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ordered.user_id
     *
     * @param userId the value for ordered.user_id
     *
     * @mbggenerated Sat Dec 21 16:33:27 CST 2019
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ordered.shipping_id
     *
     * @return the value of ordered.shipping_id
     *
     * @mbggenerated Sat Dec 21 16:33:27 CST 2019
     */
    public Integer getShippingId() {
        return shippingId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ordered.shipping_id
     *
     * @param shippingId the value for ordered.shipping_id
     *
     * @mbggenerated Sat Dec 21 16:33:27 CST 2019
     */
    public void setShippingId(Integer shippingId) {
        this.shippingId = shippingId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ordered.payment
     *
     * @return the value of ordered.payment
     *
     * @mbggenerated Sat Dec 21 16:33:27 CST 2019
     */
    public BigDecimal getPayment() {
        return payment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ordered.payment
     *
     * @param payment the value for ordered.payment
     *
     * @mbggenerated Sat Dec 21 16:33:27 CST 2019
     */
    public void setPayment(BigDecimal payment) {
        this.payment = payment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ordered.payment_type
     *
     * @return the value of ordered.payment_type
     *
     * @mbggenerated Sat Dec 21 16:33:27 CST 2019
     */
    public Integer getPaymentType() {
        return paymentType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ordered.payment_type
     *
     * @param paymentType the value for ordered.payment_type
     *
     * @mbggenerated Sat Dec 21 16:33:27 CST 2019
     */
    public void setPaymentType(Integer paymentType) {
        this.paymentType = paymentType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ordered.postage
     *
     * @return the value of ordered.postage
     *
     * @mbggenerated Sat Dec 21 16:33:27 CST 2019
     */
    public Integer getPostage() {
        return postage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ordered.postage
     *
     * @param postage the value for ordered.postage
     *
     * @mbggenerated Sat Dec 21 16:33:27 CST 2019
     */
    public void setPostage(Integer postage) {
        this.postage = postage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ordered.status
     *
     * @return the value of ordered.status
     *
     * @mbggenerated Sat Dec 21 16:33:27 CST 2019
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ordered.status
     *
     * @param status the value for ordered.status
     *
     * @mbggenerated Sat Dec 21 16:33:27 CST 2019
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ordered.payment_time
     *
     * @return the value of ordered.payment_time
     *
     * @mbggenerated Sat Dec 21 16:33:27 CST 2019
     */
    public Date getPaymentTime() {
        return paymentTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ordered.payment_time
     *
     * @param paymentTime the value for ordered.payment_time
     *
     * @mbggenerated Sat Dec 21 16:33:27 CST 2019
     */
    public void setPaymentTime(Date paymentTime) {
        this.paymentTime = paymentTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ordered.send_time
     *
     * @return the value of ordered.send_time
     *
     * @mbggenerated Sat Dec 21 16:33:27 CST 2019
     */
    public Date getSendTime() {
        return sendTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ordered.send_time
     *
     * @param sendTime the value for ordered.send_time
     *
     * @mbggenerated Sat Dec 21 16:33:27 CST 2019
     */
    public void setSendTime(Date sendTime) {
        this.sendTime = sendTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ordered.end_time
     *
     * @return the value of ordered.end_time
     *
     * @mbggenerated Sat Dec 21 16:33:27 CST 2019
     */
    public Date getEndTime() {
        return endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ordered.end_time
     *
     * @param endTime the value for ordered.end_time
     *
     * @mbggenerated Sat Dec 21 16:33:27 CST 2019
     */
    public void setEndTime(Date endTime) {
        this.endTime = endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ordered.close_time
     *
     * @return the value of ordered.close_time
     *
     * @mbggenerated Sat Dec 21 16:33:27 CST 2019
     */
    public Date getCloseTime() {
        return closeTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ordered.close_time
     *
     * @param closeTime the value for ordered.close_time
     *
     * @mbggenerated Sat Dec 21 16:33:27 CST 2019
     */
    public void setCloseTime(Date closeTime) {
        this.closeTime = closeTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ordered.create_time
     *
     * @return the value of ordered.create_time
     *
     * @mbggenerated Sat Dec 21 16:33:27 CST 2019
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ordered.create_time
     *
     * @param createTime the value for ordered.create_time
     *
     * @mbggenerated Sat Dec 21 16:33:27 CST 2019
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ordered.update_time
     *
     * @return the value of ordered.update_time
     *
     * @mbggenerated Sat Dec 21 16:33:27 CST 2019
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ordered.update_time
     *
     * @param updateTime the value for ordered.update_time
     *
     * @mbggenerated Sat Dec 21 16:33:27 CST 2019
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    @Override
    public String toString() {
        return "Ordered{" +
                "id=" + id +
                ", orderNo=" + orderNo +
                ", userId=" + userId +
                ", shippingId=" + shippingId +
                ", payment=" + payment +
                ", paymentType=" + paymentType +
                ", postage=" + postage +
                ", status=" + status +
                ", paymentTime=" + paymentTime +
                ", sendTime=" + sendTime +
                ", endTime=" + endTime +
                ", closeTime=" + closeTime +
                ", createTime=" + createTime +
                ", updateTime=" + updateTime +
                '}';
    }
}