package demo.model;

import java.util.Date;

// 支付信息表
public class Pay {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pay.id
     *
     * @mbggenerated Thu Nov 28 09:31:39 CST 2019
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pay.user_id
     *
     * @mbggenerated Thu Nov 28 09:31:39 CST 2019
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pay.order_no
     *
     * @mbggenerated Thu Nov 28 09:31:39 CST 2019
     */
    private Long orderNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pay.pay_platform
     *
     * @mbggenerated Thu Nov 28 09:31:39 CST 2019
     */
    private Integer payPlatform;  //支付平台:1-支付宝,2-微信

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pay.platform_number
     *
     * @mbggenerated Thu Nov 28 09:31:39 CST 2019
     */
    private String platformNumber;  // 支付宝支付流水号

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pay.platform_status
     *
     * @mbggenerated Thu Nov 28 09:31:39 CST 2019
     */
    private String platformStatus;  // 支付宝支付状态

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pay.create_time
     *
     * @mbggenerated Thu Nov 28 09:31:39 CST 2019
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pay.update_time
     *
     * @mbggenerated Thu Nov 28 09:31:39 CST 2019
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pay.id
     *
     * @return the value of pay.id
     *
     * @mbggenerated Thu Nov 28 09:31:39 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pay.id
     *
     * @param id the value for pay.id
     *
     * @mbggenerated Thu Nov 28 09:31:39 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pay.user_id
     *
     * @return the value of pay.user_id
     *
     * @mbggenerated Thu Nov 28 09:31:39 CST 2019
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pay.user_id
     *
     * @param userId the value for pay.user_id
     *
     * @mbggenerated Thu Nov 28 09:31:39 CST 2019
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pay.order_no
     *
     * @return the value of pay.order_no
     *
     * @mbggenerated Thu Nov 28 09:31:39 CST 2019
     */
    public Long getOrderNo() {
        return orderNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pay.order_no
     *
     * @param orderNo the value for pay.order_no
     *
     * @mbggenerated Thu Nov 28 09:31:39 CST 2019
     */
    public void setOrderNo(Long orderNo) {
        this.orderNo = orderNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pay.pay_platform
     *
     * @return the value of pay.pay_platform
     *
     * @mbggenerated Thu Nov 28 09:31:39 CST 2019
     */
    public Integer getPayPlatform() {
        return payPlatform;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pay.pay_platform
     *
     * @param payPlatform the value for pay.pay_platform
     *
     * @mbggenerated Thu Nov 28 09:31:39 CST 2019
     */
    public void setPayPlatform(Integer payPlatform) {
        this.payPlatform = payPlatform;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pay.platform_number
     *
     * @return the value of pay.platform_number
     *
     * @mbggenerated Thu Nov 28 09:31:39 CST 2019
     */
    public String getPlatformNumber() {
        return platformNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pay.platform_number
     *
     * @param platformNumber the value for pay.platform_number
     *
     * @mbggenerated Thu Nov 28 09:31:39 CST 2019
     */
    public void setPlatformNumber(String platformNumber) {
        this.platformNumber = platformNumber == null ? null : platformNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pay.platform_status
     *
     * @return the value of pay.platform_status
     *
     * @mbggenerated Thu Nov 28 09:31:39 CST 2019
     */
    public String getPlatformStatus() {
        return platformStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pay.platform_status
     *
     * @param platformStatus the value for pay.platform_status
     *
     * @mbggenerated Thu Nov 28 09:31:39 CST 2019
     */
    public void setPlatformStatus(String platformStatus) {
        this.platformStatus = platformStatus == null ? null : platformStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pay.create_time
     *
     * @return the value of pay.create_time
     *
     * @mbggenerated Thu Nov 28 09:31:39 CST 2019
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pay.create_time
     *
     * @param createTime the value for pay.create_time
     *
     * @mbggenerated Thu Nov 28 09:31:39 CST 2019
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pay.update_time
     *
     * @return the value of pay.update_time
     *
     * @mbggenerated Thu Nov 28 09:31:39 CST 2019
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pay.update_time
     *
     * @param updateTime the value for pay.update_time
     *
     * @mbggenerated Thu Nov 28 09:31:39 CST 2019
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}