package demo.model;

public class ProductWithBLOBs extends Product {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.sub_images
     *
     * @mbggenerated Thu Nov 28 09:31:39 CST 2019
     */
    private String subImages;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.detail
     *
     * @mbggenerated Thu Nov 28 09:31:39 CST 2019
     */
    private String detail;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.sub_images
     *
     * @return the value of product.sub_images
     *
     * @mbggenerated Thu Nov 28 09:31:39 CST 2019
     */
    public String getSubImages() {
        return subImages;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.sub_images
     *
     * @param subImages the value for product.sub_images
     *
     * @mbggenerated Thu Nov 28 09:31:39 CST 2019
     */
    public void setSubImages(String subImages) {
        this.subImages = subImages == null ? null : subImages.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.detail
     *
     * @return the value of product.detail
     *
     * @mbggenerated Thu Nov 28 09:31:39 CST 2019
     */
    public String getDetail() {
        return detail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.detail
     *
     * @param detail the value for product.detail
     *
     * @mbggenerated Thu Nov 28 09:31:39 CST 2019
     */
    public void setDetail(String detail) {
        this.detail = detail == null ? null : detail.trim();
    }
}