package demo.mapper;

import demo.model.Cart;
import demo.model.CartExample;

import java.util.Date;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CartMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cart
     *
     * @mbggenerated Thu Nov 28 09:31:39 CST 2019
     */
    int countByExample(CartExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cart
     *
     * @mbggenerated Thu Nov 28 09:31:39 CST 2019
     */
    int deleteByExample(CartExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cart
     *
     * @mbggenerated Thu Nov 28 09:31:39 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cart
     *
     * @mbggenerated Thu Nov 28 09:31:39 CST 2019
     */
    int insert(Cart record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cart
     *
     * @mbggenerated Thu Nov 28 09:31:39 CST 2019
     */
    int insertSelective(Cart record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cart
     *
     * @mbggenerated Thu Nov 28 09:31:39 CST 2019
     */
    List<Cart> selectByExample(CartExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cart
     *
     * @mbggenerated Thu Nov 28 09:31:39 CST 2019
     */
    Cart selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cart
     *
     * @mbggenerated Thu Nov 28 09:31:39 CST 2019
     */
    int updateByExampleSelective(@Param("record") Cart record, @Param("example") CartExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cart
     *
     * @mbggenerated Thu Nov 28 09:31:39 CST 2019
     */
    int updateByExample(@Param("record") Cart record, @Param("example") CartExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cart
     *
     * @mbggenerated Thu Nov 28 09:31:39 CST 2019
     */
    int updateByPrimaryKeySelective(Cart record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cart
     *
     * @mbggenerated Thu Nov 28 09:31:39 CST 2019
     */
    int updateByPrimaryKey(Cart record);

    // 1.购物车List列表
    List<Cart> selectCartByUserId(int id);

    // 查询check=0，即未勾选的数量
    int selectCartProductCheckedStatusByUserId(Integer userId);

    // 2.购物车添加商品
    Cart selectCartByProductIdAndUserId(@Param("userId") Integer userId,@Param("productId") Integer productId);

    // 4.移除购物车某个产品
    int deleteProducts(@Param("userId") Integer userId,@Param("productIdList") List<String> productIdList);

    // 5.购物车选中某个商品
    int selectChecked(@Param("userId") Integer userId, @Param("productId") Integer productId, @Param("count") int count,
                      @Param("date")Date date);

    // 7.查询在购物车里的产品数量
    int getCountByUserId(Integer userId);
}