package demo.mapper;

import demo.model.Ordered;
import demo.model.OrderedExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface OrderedMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ordered
     *
     * @mbggenerated Sat Dec 21 16:33:27 CST 2019
     */
    int countByExample(OrderedExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ordered
     *
     * @mbggenerated Sat Dec 21 16:33:27 CST 2019
     */
    int deleteByExample(OrderedExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ordered
     *
     * @mbggenerated Sat Dec 21 16:33:27 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ordered
     *
     * @mbggenerated Sat Dec 21 16:33:27 CST 2019
     */
    int insert(Ordered record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ordered
     *
     * @mbggenerated Sat Dec 21 16:33:27 CST 2019
     */
    int insertSelective(Ordered record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ordered
     *
     * @mbggenerated Sat Dec 21 16:33:27 CST 2019
     */
    List<Ordered> selectByExample(OrderedExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ordered
     *
     * @mbggenerated Sat Dec 21 16:33:27 CST 2019
     */
    Ordered selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ordered
     *
     * @mbggenerated Sat Dec 21 16:33:27 CST 2019
     */
    int updateByExampleSelective(@Param("record") Ordered record, @Param("example") OrderedExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ordered
     *
     * @mbggenerated Sat Dec 21 16:33:27 CST 2019
     */
    int updateByExample(@Param("record") Ordered record, @Param("example") OrderedExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ordered
     *
     * @mbggenerated Sat Dec 21 16:33:27 CST 2019
     */
    int updateByPrimaryKeySelective(Ordered record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ordered
     *
     * @mbggenerated Sat Dec 21 16:33:27 CST 2019
     */
    int updateByPrimaryKey(Ordered record);

    // 3.订单List
    List<Ordered> selectByUserId(Integer userId);

    Ordered selectByOrderNo(Long orderNo);

    Ordered selectByUserIdAndOrderNo(@Param("userId") Integer userId,@Param("orderNo") Long orderNo);

    // 1.订单List -- 后台
    List<Ordered> selectAllOrder();

    //统计个数
    int getCount();

}