package demo.mapper;

import demo.model.Pay;
import demo.model.PayExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface PayMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pay
     *
     * @mbggenerated Thu Nov 28 09:31:39 CST 2019
     */
    int countByExample(PayExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pay
     *
     * @mbggenerated Thu Nov 28 09:31:39 CST 2019
     */
    int deleteByExample(PayExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pay
     *
     * @mbggenerated Thu Nov 28 09:31:39 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pay
     *
     * @mbggenerated Thu Nov 28 09:31:39 CST 2019
     */
    int insert(Pay record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pay
     *
     * @mbggenerated Thu Nov 28 09:31:39 CST 2019
     */
    int insertSelective(Pay record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pay
     *
     * @mbggenerated Thu Nov 28 09:31:39 CST 2019
     */
    List<Pay> selectByExample(PayExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pay
     *
     * @mbggenerated Thu Nov 28 09:31:39 CST 2019
     */
    Pay selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pay
     *
     * @mbggenerated Thu Nov 28 09:31:39 CST 2019
     */
    int updateByExampleSelective(@Param("record") Pay record, @Param("example") PayExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pay
     *
     * @mbggenerated Thu Nov 28 09:31:39 CST 2019
     */
    int updateByExample(@Param("record") Pay record, @Param("example") PayExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pay
     *
     * @mbggenerated Thu Nov 28 09:31:39 CST 2019
     */
    int updateByPrimaryKeySelective(Pay record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pay
     *
     * @mbggenerated Thu Nov 28 09:31:39 CST 2019
     */
    int updateByPrimaryKey(Pay record);
}